version: "3.8"
volumes:
  postgres:
services:
  postgres:
    image: postgres:15-alpine
    container_name: sos_database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 1
    env_file:
      - .env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_PORT
    volumes:
      - postgres:$PGDATA
  app:
    depends_on:
      - postgres
    container_name: sos_api
    image: sos-server:18
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    expose:
      - $APP_PORT
    ports:
      - $APP_LOCAL_PORT:$APP_PORT
    stdin_open: true
    tty: true
    command: sh -c "npm run bootstrap && npm run migrate && npm run dev"
    # command: tail -f /dev/null
